spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: secret

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:29092