application:
  openapi-example-path-directory: examples/

spring:
  application:
    name: Payment service
    api-version: 1.0

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      delivery-timeout-ms: 120000
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true

payment:
    topic: payment

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only